### ISSUE TITLE
12 - Publishing outputs:  Host key verification failed.

### ISSUE THREAD

**Issue by acca301** [starkandwayne/concourse-tutorial#51] opened 2016-07-04 21:54 UTC
Walking through the tutorial step-by-step. Made a gist, added

<pre><code> - name: resource-gist
   type: git
   source:
     uri: git@gist.github.com:71c94aad09a4adc12ebec5ac2794bab4.git
     branch: master
</code></pre>

into 12_publishing_outputs/pipeline.yml. A build attempt fails in resource-gist with

> Cloning into '/tmp/build/get'...
> Host key verification failed.
> fatal: Could not read from remote repository.

Note this is pull, we're not at the push stage yet.

The host key is certainly not in ~/.ssh/known_hosts inside the task container. How / where can I run ssh-keyscan or push `known_hosts' there?

**Comment by drnic** [comment] 2016-07-04 23:14
AK, can I ask a favor? Can you please recreate this ticket with the concourse/git-resource project, link it to this issue and tag me as well (so I get notifications).
I'm sorry I'm not sure I know how to debug/ fix this issue myself.
Nic






On Tue, Jul 5, 2016 at 7:54 AM +1000, "Alexander Kuznetsov" <notifications@github.com> wrote:












Walking through the tutorial step-by-step. Made a gist, added

 - name: resource-gist
   type: git
   source:
     uri: git@gist.github.com:71c94aad09a4adc12ebec5ac2794bab4.git
     branch: master




into 12_publishing_outputs/pipeline.yml. A build attempt fails in resource-gist with




Cloning into '/tmp/build/get'...

Host key verification failed.

fatal: Could not read from remote repository.




Note this is pull, we're not at the push stage yet.



The host key is certainly not in ~/.ssh/known_hosts inside the task container. How / where can I run ssh-keyscan or push `known_hosts' there?

**Comment by acca301** [comment] 2016-07-05 16:28
Done.
BTW, your tutorial is great - unfortunately there is not many manuals made with such clarity.

**Comment by acca301** [comment] 2016-07-06 03:27
My bad. `|` was they key.
I usually do chomping with `|-`, thus I wrote it the way:
```yaml
  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |-
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---
```
while the working syntax is 

```yaml
  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---
```

**Comment by drnic** [comment] 2016-07-06 07:41
Getting yaml right can be hard! Thanks for letting me know you found a solution. Thanks for nice comments about the tutorial.






On Wed, Jul 6, 2016 at 1:27 PM +1000, "Dr. Alexander Kuznetsov" <notifications@github.com> wrote:












My bad. | was they key.

I usually do chomping with |-, thus I wrote it the way:

  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |-
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---



while the working syntax is 

  resources:
  - name: foo
    type: git
    source:
      uri: ...
      private_key: |
        ---BEGIN BLAH BLAH---
        .....
        ---END BLAH BLAH---

**Comment by joshuajabbour** [comment] 2016-07-19 07:55
If this `|-` typo was actually the problem (and I can't confirm it is; I'm also having auth issues but this hasn't fixed it for me), then you probably typed that because [the readme says to use `|-`](https://github.com/starkandwayne/concourse-tutorial#12---publishing-outputs).

**Comment by joshuajabbour** [comment] 2016-07-19 20:05
I don't think the problem is the `|-`. I can confirm both `private_key: |-` and `private_key: |` work, once I solved my [underlying issue](https://github.com/starkandwayne/concourse-tutorial/pull/54).

**Comment by jhunt** [comment] 2016-11-02 02:41
@joshuajabbour is your issue taken care of now?

**Comment by mkb** [comment] 2016-12-08 06:35
Sounds like this has been addressed so I'm closing it out. @joshuajabbour if there's still an issue please let us know. Thanks!

**Closed by mkb** 2016-12-08 06:35 UTC
