### ISSUE TITLE
05 Pipeline Fails with "file not found" after the step "using version of resource found in cache."

### ISSUE THREAD

**Issue by Jo3McCarthy** [starkandwayne/concourse-tutorial#108] opened 2017-10-24 15:04 UTC
I am running the Linux version of the tutorial.  After reinstalling multiple times (assuming I had made an error), I still get "file not found" after the step "using version of resource found in cache." 

Looking at the output, I notice this:
3172f4 Merge pull request #106 from starkandwayne/windows-users

It says "windows-users."  Perhaps somewhere in the pipeline there is a "hidden" reference to "windows?"  I searched through the text of all the example files and I did not find any occurrence of "windows" and I did verify that each of the tutorial yml files does contain linux.  Since I cannot complete this step, I do not know how to proceed with the rest of the tutorial.

If anybody has seen a similar issue, please reply.

Thanks,

Jo3

**Comment by drnic** [comment] 2018-04-02 05:38
I'll close this for now as in-active. I haven't been able to reproduce it. If its still happening, please reopen and accept my apologies.

**Closed by drnic** 2018-04-02 05:38 UTC

**Comment by dagomar** [comment] 2018-06-25 21:11
I'm stuck on the same step:
https://concoursetutorial.com/basics/basic-pipeline/

![image](https://user-images.githubusercontent.com/115586/41875816-51d6d42e-78cc-11e8-8a1e-91013729c392.png)
![image](https://user-images.githubusercontent.com/115586/41875848-6ca810b0-78cc-11e8-9ea7-a09aea1e5fcd.png)
```
concourse_1     | {"timestamp":"1529960886.995148897","source":"guardian","message":"guardian.api.garden-server.run.spawned","log_level":1,"data":{"handle":"1894ac82-d30f-4736-4183-79d462bac592","id":"2281ec19-135a-49c2-41f2-f9dc64f99339","session":"3.1.53","spec":{"Path":"/opt/resource/check","Dir":"","User":"root","Limits":{},"TTY":null}}}
concourse_1     | {"timestamp":"1529960886.999553442","source":"tsa","message":"tsa.connection.keepalive","log_level":1,"data":{"remote":"127.0.0.1:48978","session":"1","type":"keepalive"}}
concourse_1     | {"timestamp":"1529960889.404121399","source":"guardian","message":"guardian.api.garden-server.run.exited","log_level":1,"data":{"handle":"1894ac82-d30f-4736-4183-79d462bac592","id":"2281ec19-135a-49c2-41f2-f9dc64f99339","session":"3.1.53","status":0}}
concourse_1     | {"timestamp":"1529960889.432923079","source":"baggageclaim","message":"baggageclaim.api.volume-server.stream-out.source-path-not-found","log_level":1,"data":{"session":"4.1.104","volume":"a115909b-eb74-4e03-6362-9ccb8b9c002c"}}
concourse_1     | {"timestamp":"1529960889.433436632","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.failed-to-fetch-image","log_level":2,"data":{"build-id":24,"build-name":"2","container":"5331e67e-717a-4f96-47f1-61c837700266","error":"file not found","job_name":"job-hello-world","session":"1216.1.1"}}
concourse_1     | {"timestamp":"1529960889.438011885","source":"atc","message":"atc.create-job-build.trigger-immediately.try-start-next-pending-build.failed-to-fetch-image-for-container","log_level":2,"data":{"build-id":24,"build-name":"2","container":"5331e67e-717a-4f96-47f1-61c837700266","error":"file not found","job_name":"job-hello-world","session":"1216.1.1"}}
```

**Comment by drnic** [comment] 2018-06-25 21:33
Can I ask a favour? Could you raise this issue upstream at https://github.com/concourse/concourse/issues where the core team might be able to identify the nature of this issue?

**Comment by dagomar** [comment] 2018-06-26 08:10
Hi drnic,

Agreed. This was the only issue I found which had the same problem, but it might be caused by something upstream. As I might be doing something different in my setup I will investigate first; I am thinking perhaps my setup of the docker-compose.yml is causing this somehow. If I figure out what is going on I will report back, in the case of a real issue I will raise this upstream.

Sincerely,

Dagomar

**Comment by dagomar** [comment] 2018-06-26 09:43
Hi drnic,

it's what I thought, I altered my docker-compose.yml so it uses Traefik. I think there is something wrong in that setup because when I don't do that and use the default docker-compose it starts working. Sorry for the mixup.

Sincerely,

Dagomar
